// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQLELABqEjvhQm8M9rN_MuOug75k8Qz8',
    appId: '1:334266748803:web:06cd2960ebeee7628eb0b6',
    messagingSenderId: '334266748803',
    projectId: 'green-route-8ce34',
    authDomain: 'green-route-8ce34.firebaseapp.com',
    storageBucket: 'green-route-8ce34.firebasestorage.app',
    measurementId: 'G-FGZ86GEV0X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1YtoU7tCGaZzqChzKiEXj_fGfbwqM0ZQ',
    appId: '1:334266748803:ios:174c0aa3c442ac3c8eb0b6',
    messagingSenderId: '334266748803',
    projectId: 'green-route-8ce34',
    storageBucket: 'green-route-8ce34.firebasestorage.app',
    iosBundleId: 'com.example.greenRoute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrQLELABqEjvhQm8M9rN_MuOug75k8Qz8',
    appId: '1:334266748803:web:be1ad4e334ed66928eb0b6',
    messagingSenderId: '334266748803',
    projectId: 'green-route-8ce34',
    authDomain: 'green-route-8ce34.firebaseapp.com',
    storageBucket: 'green-route-8ce34.firebasestorage.app',
    measurementId: 'G-F7NH58VKMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoFUq2aFoStpwtnTTVvvUiHhIip5HQV0E',
    appId: '1:334266748803:android:c629a220757d3ed68eb0b6',
    messagingSenderId: '334266748803',
    projectId: 'green-route-8ce34',
    storageBucket: 'green-route-8ce34.firebasestorage.app',
  );

}